-- Superseded: the FBI UCR relations this step created now live under `src/`.
--
-- The bootstrap manifest no longer applies this file. Its content moved,
-- unchanged, to the files the `fbi_ucr_ingest` DAG re-applies on every run:
--
--   * `src/data_ingestion_toolbox/fbi_ucr/DDL/silver_fbi.sql`
--   * `src/data_ingestion_toolbox/fbi_ucr/gold_fbi/DDL/gold_fbi.sql`
--   * `src/data_ingestion_toolbox/fbi_ucr/gold_fbi/DDL/publisher.sql`
--
-- A migration is applied once by a bootstrap and never again, so relations
-- defined only here had no runtime owner: the DAG could not repair a
-- warehouse a step behind it. The file is kept so this history is findable
-- from the number a runbook or a `control` row records.
