-- Superseded: every view this step replaced is now defined under `src/`.
--
-- The bootstrap manifest no longer applies this file. It replaced the CDC,
-- FBI and USDA NASS publisher and measure-export views so each exposes one
-- row per measure identity instead of one row per published release --
-- grouping by the release watermark made the glossary harvest fail, and the
-- USDA NASS measures endpoint duplicate every measure, as soon as a second
-- release was published.
--
-- That shape is what the source-owned files now define:
--
--   * `src/data_ingestion_toolbox/cdc/gold_cdc/DDL/publisher.sql`
--   * `src/data_ingestion_toolbox/fbi_ucr/gold_fbi/DDL/publisher.sql`
--   * `src/data_ingestion_toolbox/usda_nass/gold_nass/DDL/gold_nass.sql`
--   * `src/data_ingestion_toolbox/usda_nass/gold_nass/DDL/publisher.sql`
--
-- A view body restated in a migration is a second copy that drifts, and each
-- of these was on its third. One definition, in the file the DAG re-applies.
