-- Superseded: every view this step replaced is now defined under `src/`.
--
-- The bootstrap manifest no longer applies this file. It served only rows
-- whose geography resolved from `gold_cdc.health_observation` and
-- `gold_nass.crop_observation`, and aggregated the CDC and USDA NASS
-- publishers' `valid_geo_grains` from the same rows.
--
-- `gold_fbi.crime_observation` has excluded unresolved geographies since the
-- FBI pipeline's first step; its two siblings filtered on the release status
-- alone, so `/observations` paged out rows with `geo_id: null` and a
-- `geo_level` outside the served vocabulary, and a NASS product with one
-- AGRICULTURAL DISTRICT row advertised `UNSUPPORTED` as a grain a client
-- could ask for. The rows stay in silver with the resolution ledger;
-- `unmapped` stays served, because its grain is in the vocabulary and
-- DB-003's rule is that such a miss is explicit rather than dropped.
--
-- Those predicates are part of the source-owned definitions now:
--
--   * `src/data_ingestion_toolbox/cdc/gold_cdc/DDL/gold_cdc.sql`
--   * `src/data_ingestion_toolbox/cdc/gold_cdc/DDL/publisher.sql`
--   * `src/data_ingestion_toolbox/fbi_ucr/gold_fbi/DDL/publisher.sql`
--   * `src/data_ingestion_toolbox/usda_nass/gold_nass/DDL/gold_nass.sql`
--   * `src/data_ingestion_toolbox/usda_nass/gold_nass/DDL/publisher.sql`
