-- Superseded: `gold_fbi.metric_publisher` is now defined under `src/`.
--
-- The bootstrap manifest no longer applies this file. It replaced the view so
-- its `valid_geo_grains` go through `gold_glossary.geo_grain` like every other
-- publisher's, and its own note recorded why it had to be a new step at all:
-- FBI's was "the one publisher whose last definition sits in a migration
-- rather than a phase file, and that step is not edited in place".
--
-- It sits in a phase file now, which is what this step was working around:
-- `src/data_ingestion_toolbox/fbi_ucr/gold_fbi/DDL/publisher.sql`.
