"""A deterministic rendering of the warehouse schema, for review as a diff.

The manifest is the upgrade path: re-running it against an existing database
*is* the migration. Nothing proved that a DDL edit under `src/` reached a
warehouse the way its author expected, or that a phase file later in the
manifest did not overwrite a migration earlier in it. Both are silent, and
both are schema changes nobody reviewed as one.

This renders what a bootstrapped warehouse actually holds -- relations,
columns with types and nullability, constraints, indexes and view bodies --
into a stable text file. `tests/sql/warehouse_schema_snapshot.txt` is checked
in, so a change to the schema arrives as a reviewable hunk in the same way the
OpenAPI contract digest does.

Regenerate after a deliberate change::

    RUN_INTEGRATION_TESTS=1 TEST_POSTGRES_HOST=... TEST_POSTGRES_PORT=... \\
      TEST_POSTGRES_USER=... TEST_POSTGRES_PASSWORD=... \\
      TEST_POSTGRES_DATABASE=..._test \\
      python -m tests.support.schema_snapshot --write

Read from `pg_catalog` rather than from the DDL text, because the DDL is the
input and the question is what the database ended up with.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[2]
SNAPSHOT_PATH = REPOSITORY_ROOT / "tests/sql/warehouse_schema_snapshot.txt"

#: Schemas the warehouse manifest owns. Everything else is excluded, and the
#: two reasons differ.
#:
#: PostGIS's own schemas and `public` are the extension's business: they change
#: when it is upgraded, which is not a change to this repository's schema.
#:
#: `app_api` is this repository's, and is still excluded, because it is not the
#: manifest's. `sql/bootstrap/002_app_api.sql` is applied separately -- ADR-0003
#: makes application storage optional, a deployment may not have it, and
#: `test_api_reader_privileges` applies it part-way through the tier. Including
#: it would make this snapshot depend on which tests had run, which is the one
#: thing a snapshot must not do. What it describes is exactly what `DB-052`
#: reapplies: the schema the manifest produces.
EXCLUDED_SCHEMAS = (
    "pg_catalog",
    "information_schema",
    "public",
    "tiger",
    "tiger_data",
    "topology",
    "app_api",
)

#: `relispartition` is excluded, and the reason is that a partition's shape is
#: not its own. PostgreSQL requires every partition to carry the parent's
#: columns in the parent's order, and an index created on the parent is created
#: on each partition; so rendering 37 ACS year partitions in full added 1,933
#: lines saying the same thing 37 times, which is how a reviewable diff stops
#: being read. What *is* reviewable -- the strategy, the key, and which ranges
#: exist -- is rendered on the parent below, and
#: `test_every_partition_carries_its_parents_columns` checks the guarantee this
#: omission rests on rather than trusting it.
_RELATIONS = """
SELECT n.nspname, c.relname, c.relkind
  FROM pg_class AS c
  JOIN pg_namespace AS n ON n.oid = c.relnamespace
 WHERE c.relkind IN ('r', 'p', 'v', 'm')
   AND NOT c.relispartition
   AND n.nspname <> ALL(%s)
 ORDER BY n.nspname, c.relname
"""

_PARTITIONS = """
SELECT c.relname, pg_get_expr(c.relpartbound, c.oid)
  FROM pg_inherits AS i
  JOIN pg_class AS c ON c.oid = i.inhrelid
 WHERE i.inhparent = %s
 ORDER BY c.relname
"""

_COLUMNS = """
SELECT a.attname,
       pg_catalog.format_type(a.atttypid, a.atttypmod),
       a.attnotnull,
       COALESCE(pg_get_expr(d.adbin, d.adrelid), '')
  FROM pg_attribute AS a
  LEFT JOIN pg_attrdef AS d
    ON d.adrelid = a.attrelid AND d.adnum = a.attnum
 WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
"""

_CONSTRAINTS = """
SELECT conname, pg_get_constraintdef(oid)
  FROM pg_constraint
 WHERE conrelid = %s
 ORDER BY conname
"""

_INDEXES = """
SELECT indexname, indexdef
  FROM pg_indexes
 WHERE schemaname = %s AND tablename = %s
 ORDER BY indexname
"""


def render(connection: Any) -> str:
    """The whole warehouse schema, as one deterministic block of text."""
    lines: list[str] = [
        "# Warehouse schema snapshot.",
        "#",
        "# Generated by `python -m tests.support.schema_snapshot --write` from a",
        "# bootstrapped warehouse. Do not hand-edit: regenerate, and review the",
        "# diff. A change here is a schema change, and an unexplained one is the",
        "# thing this file exists to surface.",
        "",
    ]
    with connection.cursor() as cursor:
        cursor.execute(_RELATIONS, (list(EXCLUDED_SCHEMAS),))
        relations = cursor.fetchall()
        for schema, name, kind in relations:
            qualified = f"{schema}.{name}"
            lines.append(f"{kind} {qualified}")

            cursor.execute("SELECT %s::regclass::oid", (qualified,))
            oid = cursor.fetchone()[0]

            cursor.execute(_COLUMNS, (oid,))
            for column, datatype, notnull, default in cursor.fetchall():
                flags = " NOT NULL" if notnull else ""
                shown = f" DEFAULT {default}" if default else ""
                lines.append(f"    column {column} {datatype}{flags}{shown}")

            cursor.execute(_CONSTRAINTS, (oid,))
            for constraint, definition in cursor.fetchall():
                lines.append(f"    constraint {constraint} {definition}")

            if kind in ("r", "p", "m"):
                cursor.execute(_INDEXES, (schema, name))
                for index, definition in cursor.fetchall():
                    lines.append(f"    index {index} {definition}")

            if kind == "p":
                cursor.execute("SELECT pg_get_partkeydef(%s)", (oid,))
                lines.append(f"    partitioned by {cursor.fetchone()[0]}")
                cursor.execute(_PARTITIONS, (oid,))
                for partition, bound in cursor.fetchall():
                    lines.append(f"    partition {partition} {bound}")

            if kind in ("v", "m"):
                cursor.execute("SELECT pg_get_viewdef(%s, true)", (oid,))
                body = cursor.fetchone()[0].strip()
                for line in body.splitlines():
                    lines.append(f"    body {line.rstrip()}")
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _connect() -> Any:
    from tests.support.postgres import PostgresTestConfig

    config = PostgresTestConfig.from_environment()
    if config is None:
        raise SystemExit(
            "Set the TEST_POSTGRES_* variables; the snapshot is rendered from a "
            "bootstrapped disposable warehouse, not from the DDL text."
        )
    return config.connect()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="overwrite the checked-in snapshot with the current schema",
    )
    arguments = parser.parse_args(argv)

    connection = _connect()
    try:
        rendered = render(connection)
    finally:
        connection.close()

    if arguments.write:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {SNAPSHOT_PATH.relative_to(REPOSITORY_ROOT).as_posix()}")
        return 0

    if not SNAPSHOT_PATH.exists():
        print("no snapshot is checked in; run with --write", file=sys.stderr)
        return 1
    if SNAPSHOT_PATH.read_text(encoding="utf-8") == rendered:
        print("the warehouse matches the checked-in snapshot")
        return 0
    print("the warehouse and the checked-in snapshot differ", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
