#!/usr/bin/env python3
"""Provision and optionally configure a least-privilege API/Martin database role."""

from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path

import psycopg2
from psycopg2 import sql


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def value(values: dict[str, str], key: str, default: str = "") -> str:
    return os.getenv(key) or values.get(key, default)


def update_env_file(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    remaining = dict(updates)
    output: list[str] = []
    for line in lines:
        if "=" in line and not line.lstrip().startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in remaining:
                output.append(f"{key}={remaining.pop(key)}")
                continue
        output.append(line)
    if remaining:
        if output and output[-1]:
            output.append("")
        output.append(
            "# Read-only public serving role (generated by provision_api_readonly.py)."
        )
        output.extend(f"{key}={item}" for key, item in remaining.items())
    path.write_text("\n".join(output) + "\n", encoding="utf-8")


def provision(values: dict[str, str], role_name: str, role_password: str) -> None:
    database = value(values, "ANALYTICS_DB_NAME", "population_etl")
    conn = psycopg2.connect(
        host=value(values, "ANALYTICS_DB_HOST", "localhost"),
        port=int(value(values, "ANALYTICS_DB_PORT", "5432")),
        user=value(values, "ANALYTICS_DB_USER", "postgres"),
        password=value(values, "ANALYTICS_DB_PASSWORD"),
        dbname=database,
        connect_timeout=10,
    )
    conn.autocommit = True
    try:
        with conn.cursor() as cursor:
            cursor.execute("SELECT current_user")
            owner = str(cursor.fetchone()[0])
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role_name,))
            if cursor.fetchone():
                cursor.execute(
                    sql.SQL("ALTER ROLE {} LOGIN PASSWORD %s").format(
                        sql.Identifier(role_name)
                    ),
                    (role_password,),
                )
            else:
                cursor.execute(
                    sql.SQL("CREATE ROLE {} LOGIN PASSWORD %s").format(
                        sql.Identifier(role_name)
                    ),
                    (role_password,),
                )

            cursor.execute(
                sql.SQL("ALTER ROLE {} SET default_transaction_read_only = on").format(
                    sql.Identifier(role_name)
                )
            )
            cursor.execute(
                sql.SQL("GRANT CONNECT ON DATABASE {} TO {}").format(
                    sql.Identifier(database), sql.Identifier(role_name)
                )
            )
            for schema in (
                "gold",
                "gold_glossary",
                "gold_bls",
                "gold_census",
                "gold_fred",
            ):
                cursor.execute(
                    "SELECT 1 FROM pg_namespace WHERE nspname = %s", (schema,)
                )
                if not cursor.fetchone():
                    continue
                cursor.execute(
                    sql.SQL("GRANT USAGE ON SCHEMA {} TO {}").format(
                        sql.Identifier(schema), sql.Identifier(role_name)
                    )
                )
                cursor.execute(
                    sql.SQL("GRANT SELECT ON ALL TABLES IN SCHEMA {} TO {}").format(
                        sql.Identifier(schema), sql.Identifier(role_name)
                    )
                )
                cursor.execute(
                    sql.SQL(
                        "ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA {} "
                        "GRANT SELECT ON TABLES TO {}"
                    ).format(
                        sql.Identifier(owner),
                        sql.Identifier(schema),
                        sql.Identifier(role_name),
                    )
                )
    finally:
        conn.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env-file", default="infra/docker/stack.external.env")
    parser.add_argument("--role-name", default="")
    parser.add_argument("--write-env", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    env_path = Path(args.env_file)
    values = load_env_file(env_path)
    role_name = args.role_name or value(values, "ANALYTICS_API_DB_USER", "api_reader")
    role_password = value(values, "ANALYTICS_API_DB_PASSWORD") or secrets.token_urlsafe(
        32
    )
    provision(values, role_name, role_password)
    if args.write_env:
        update_env_file(
            env_path,
            {
                "ANALYTICS_API_DB_USER": role_name,
                "ANALYTICS_API_DB_PASSWORD": role_password,
            },
        )
    print(
        f"Provisioned read-only role '{role_name}' for serving schemas "
        "gold, gold_glossary, gold_bls, gold_census, and gold_fred when present."
    )
    if args.write_env:
        print(f"Updated {env_path} with serving credentials (password not displayed).")
    else:
        print(
            "Re-run with --write-env to store generated serving credentials in the env file."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
