#!/usr/bin/env python3
"""Provision and optionally configure a least-privilege API/Martin database role."""

from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path

import psycopg2
from psycopg2 import sql

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
#: The one reviewed statement of what the serving role may read.
BOOTSTRAP_SQL = REPOSITORY_ROOT / "sql/bootstrap/001_api_readonly.sql"
#: The role that holds the grants. A differently named login joins it.
POLICY_ROLE = "api_reader"


def load_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def value(values: dict[str, str], key: str, default: str = "") -> str:
    return os.getenv(key) or values.get(key, default)


def update_env_file(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    remaining = dict(updates)
    output: list[str] = []
    for line in lines:
        if "=" in line and not line.lstrip().startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in remaining:
                output.append(f"{key}={remaining.pop(key)}")
                continue
        output.append(line)
    if remaining:
        if output and output[-1]:
            output.append("")
        output.append(
            "# Read-only public serving role (generated by provision_api_readonly.py)."
        )
        output.extend(f"{key}={item}" for key, item in remaining.items())
    path.write_text("\n".join(output) + "\n", encoding="utf-8")


def provision(values: dict[str, str], role_name: str, role_password: str) -> None:
    """Apply the reviewed policy, then give one login role a password.

    The grants are not here. `sql/bootstrap/001_api_readonly.sql` is the single
    statement of what the serving role may read, and this function applies that
    file rather than repeating it -- the two used to be separate
    implementations of one policy and had already drifted: the file granted
    SELECT on sequences and a default privilege for them, and this script
    granted neither.

    What stays here is the part a checked-in file must not carry: a password.

    `api_reader` is the *policy* role and holds every grant. A deployment that
    wants a differently named login -- `ANALYTICS_API_DB_USER` -- gets one that
    is a member of it, rather than a second role someone has to remember to
    grant the same things to. Membership is what makes one reviewed policy
    cover both shapes.
    """
    conn = psycopg2.connect(
        host=value(values, "ANALYTICS_DB_HOST", "localhost"),
        port=int(value(values, "ANALYTICS_DB_PORT", "5432")),
        user=value(values, "ANALYTICS_DB_USER", "postgres"),
        password=value(values, "ANALYTICS_DB_PASSWORD"),
        dbname=value(values, "ANALYTICS_DB_NAME", "population_etl"),
        connect_timeout=10,
    )
    conn.autocommit = True
    try:
        with conn.cursor() as cursor:
            cursor.execute(BOOTSTRAP_SQL.read_text(encoding="utf-8"))

            cursor.execute(
                sql.SQL("ALTER ROLE {} LOGIN PASSWORD %s").format(
                    sql.Identifier(POLICY_ROLE)
                ),
                (role_password,),
            )
            if role_name == POLICY_ROLE:
                return

            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role_name,))
            statement = (
                "ALTER ROLE {} LOGIN PASSWORD %s"
                if cursor.fetchone()
                else ("CREATE ROLE {} LOGIN PASSWORD %s")
            )
            cursor.execute(
                sql.SQL(statement).format(sql.Identifier(role_name)), (role_password,)
            )
            # Set on the member as well as on the policy role: a role-level
            # setting is not inherited through membership, so a login that
            # skipped this would be a writable session holding read-only
            # grants -- harmless today and exactly the kind of gap that stops
            # being harmless when a grant is widened.
            cursor.execute(
                sql.SQL("ALTER ROLE {} SET default_transaction_read_only = on").format(
                    sql.Identifier(role_name)
                )
            )
            cursor.execute(
                sql.SQL("GRANT {} TO {}").format(
                    sql.Identifier(POLICY_ROLE), sql.Identifier(role_name)
                )
            )
    finally:
        conn.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env-file", default="infra/docker/stack.external.env")
    parser.add_argument("--role-name", default="")
    parser.add_argument("--write-env", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    env_path = Path(args.env_file)
    values = load_env_file(env_path)
    role_name = args.role_name or value(values, "ANALYTICS_API_DB_USER", "api_reader")
    role_password = value(values, "ANALYTICS_API_DB_PASSWORD") or secrets.token_urlsafe(
        32
    )
    provision(values, role_name, role_password)
    if args.write_env:
        update_env_file(
            env_path,
            {
                "ANALYTICS_API_DB_USER": role_name,
                "ANALYTICS_API_DB_PASSWORD": role_password,
            },
        )
    print(
        f"Applied sql/bootstrap/001_api_readonly.sql and provisioned "
        f"'{role_name}'"
        + ("" if role_name == "api_reader" else " as a member of api_reader")
        + "."
    )
    if args.write_env:
        print(f"Updated {env_path} with serving credentials (password not displayed).")
    else:
        print(
            "Re-run with --write-env to store generated serving credentials in the env file."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
